### ISSUE TITLE
App Crashes when using bundle.config with abi splits set to negate.

### ISSUE THREAD

**Issue by dellis1972** [dotnet/android#8979]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.net8.0-android, .net9.0-android

### Description

When using a bundle.config with the following contents 

```json
{
	"compression": { },
	"optimizations": {
		"splitsConfig": {
			"splitDimension": [
				{
						"value": "ABI",
						"negate": true
				}
			 ],
		}
	}
}
```

the app crashes at runtime with the following error.

```
At least a single application lib directory must be added"
```

### Steps to Reproduce

1. Download the attached repo app.
2. Build and run it using the latest main of .net android.

### Did you find any workaround?

Changing `"negate": true` to `"negate": false` fixes the issue.

**Comment by dellis1972** [comment]
[MyApp.zip](https://github.com/xamarin/xamarin-android/files/15422232/MyApp.zip)

**Comment by dellis1972** [comment]
[logcat-failed.log.zip](https://github.com/xamarin/xamarin-android/files/15433400/logcat-failed.log.zip)

**Comment by dellis1972** [comment]
So I tried this patch https://gist.github.com/dellis1972/2a3f62c4b7728dd33c621d823640fba7

This adds an additional fallback to 

```
if (Util::ends_with (apk, SharedConstants::split_config_abi_apk_name)) {
```

```
if (Util::ends_with (apk, SharedConstants::split_config_abi_apk_name) || Util::ends_with (apk, SharedConstants::base_apk_name)) {
```

Now I get an error

```
Abort message: '/Users/dean/Documents/Sandbox/Xamarin/xamarin-android/src/native/monodroid/embedded-assemblies.hh:180 (ensure_valid_assembly_stores): Invalid or incomplete assembly store data
```

So something about the assembly stores gets messed up by this.

**Comment by grendello** [comment]
The problem is here https://github.com/xamarin/xamarin-android/blob/main/src/native/runtime-base/android-system.cc#L740-L747

Previously, whenever split configs were present, the shared libraries always lived in a file named `split_config.ARCH.apk` (with `ARCH` replaced by e.g. `arm64`) and so, for performance reasons, we skip scanning anything that's not a file named like that **if** we detect that `split_config.*` files exist.

In this case the split files do exist, but shared libraries are all in `base.apk` and the architecture-specific split config doesn't exist at all:

```shell
$ adb shell run-as com.xamarin.runapplicationwithassetpacktextureformats ls -l /data/app/~~SiaOe7UQLju6w_cxUf4LsA==/com.xamarin.runapplicationwithassetpacktextureformats-Z7cymJN9yrWULwTPJncm_Q==/
total 28479
-rw-r--r-- 1 system system 29080982 2024-05-24 18:07 base.apk
drwxr-xr-x 3 system system     3452 2024-05-24 18:07 lib
-rw-r--r-- 1 system system     8478 2024-05-24 18:07 split_assetpack1.apk
-rw-r--r-- 1 system system     8559 2024-05-24 18:07 split_assetpack1.config.astc.apk
-rw-r--r-- 1 system system    16808 2024-05-24 18:07 split_config.xxxhdpi.apk
```

I need to think about it a bit, so that we don't hurt startup performance with the fix.
