### ISSUE TITLE
Bad performance while using OData client vs using HttpClient on Android

### ISSUE THREAD

**Issue by marcmognol** [dotnet/android#9054]
### Android framework version

net8.0-android

### Affected platform version

.NET 8.0.302

### Description

I'm in the process to develop a MAUI application for my company. This application will connect to OData endpoints.
To achieve my goal, I followed the Microsoft documentation https://learn.microsoft.com/en-us/odata/client/getting-started to connect my project to our OData endpoint.

But, I'm experiencing very bad performance while using the application, even in Release mode.

I've got the idea to use classic HttpClient to compare the performance, and HttpClient is 2x faster than OData client.

### Steps to Reproduce

1. Clone the reproduction project repository (https://github.com/marcmognol/Maui.OData.PerformanceIssue/)
2. Run the application with Android emulator (MAUI workload is required)
3. Click on HttpClient button (multiple times)
4. Click on ODATA button (multiple times)
5. Compare request response time

![341830954-d27cea9a-bf5c-44ab-b4a7-e758e5b2c033](https://github.com/dotnet/android/assets/8171300/8ba9c4f8-77e8-4e94-9cca-77b7b7a6aa48)

### Did you find any workaround?

Considering using HttpClient, performance are way better.
I also tried to use Simple.OData.Client but same bad performance with it.

![342105968-798e5146-5fa2-47f1-a4a0-494d3e9f30a2](https://github.com/dotnet/android/assets/8171300/fcbfca83-fe3e-4639-a118-6ec938fd63ce)

https://github.com/dotnet/maui/issues/23185

**Comment by grendello** [comment]
Considering that OData isn't part of .NET for Android, I'm not sure how we can help you here.  By looking at your test code (and briefly at `OData` code), I noticed that your OData handler has [this loop](https://github.com/marcmognol/Maui.OData.PerformanceIssue/blob/main/Infrastructure/MyODataRepository.cs#L13-L16) (`serviceRoot` should be a constant, too - not much performance penalty here but still non-zero):

```csharp
public static async Task GetAsync()
{
   var serviceRoot = "https://services.odata.org/V4/TripPinServiceRW/";
   var context = new DefaultContainer(new Uri(serviceRoot));

   IEnumerable<Person> people = await context.People.ExecuteAsync();
   foreach (var person in people)
   {
      Console.WriteLine("{0} {1}", person.FirstName, person.LastName);
   }
}
```

which is very expensive on Android, since each message has to be routed to the logcat service which runs outside of your app, as an operating system service.  For that reason alone I'd expect this code to be much slower than your HttpClient code:

```csharp
public static async Task<ODataResponse?> GetAsync()
{
   var httpClient = new HttpClient();

   return await httpClient.GetFromJsonAsync<ODataResponse>("https://services.odata.org/V4/(S(r5behdg3orwkze3bmwcnjwqm))/TripPinServiceRW/People");
}
```

Furthermore, note that `OData` uses `HttpClient` internally too.  Slower performance using `OData` code is expected, considering the layers of code between your call to `OData` client and their invocation of `HttpClient` request.

If you think `OData` performance is lacking, I'd suggest opening an issue in [their repository](https://github.com/OData/odata.net) - they should be able to help you more than we can.

I hope you find a solution to your performance problem, good luck! :)
