### ISSUE TITLE
AndroidMavenLibrary is not able to be resolved from Maven

### ISSUE THREAD

**Issue by TheHighriser** [dotnet/android#9316]
### Android framework version

net9.0-android

### Affected platform version

9.0.100-rc.1.24452.12

### Description

I am trying to resolve all transitive dependencies that my library has and I am stuck at all libraries which are starting with "androidx.". For example: androidx.room:room-runtime

This library is visible on Maven: https://mvnrepository.com/artifact/androidx.room/room-runtime/2.6.1

It tried to use:

`<AndroidMavenLibrary Include="androidx.room:room-runtime" Version="2.6.1" Bind="false" />`

But it results in the following error:

`error XA4236: Cannot download Maven artifact 'androidx.room:room-runtime'.
error XA4236: - room-runtime-2.6.1.jar: Response status code does not indicate success: 404 (Not Found).
error XA4236: - room-runtime-2.6.1.aar: Response status code does not indicate success: 404 (Not Found).`

If I look at the links in Maven they are a bit different then for other libs. Could this be an issue? Or is this an actual bug?

### Steps to Reproduce

Add `<AndroidMavenLibrary Include="androidx.room:room-runtime" Version="2.6.1" Bind="false" />` to your Android binding library.

**Comment by jpobst** [comment]
This library does not come from Maven Central, which is the default.  It comes from Google's Maven repository, you will need to specify that with the `Repository` attribute:

https://learn.microsoft.com/en-us/dotnet/android/binding-libs/advanced-concepts/android-maven-library#options

Additionally, Microsoft maintains a binding of this library you may prefer to use rather than binding your own:
https://www.nuget.org/packages/Xamarin.AndroidX.Room.Runtime

**Comment by TheHighriser** [comment]
Thanks! I didn't see this in the documentation.

Yeah in the beginning I tried to use packages from Nuget, but I got into a clash of version pretty fast (as I have several transitive dependencies). Specifying them manually works better especially because I can deactivate the creation of the binding which I don't need anyways.
